/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries.$libraryId'
import { Route as ShelvesShelfIdRouteImport } from './routes/shelves.$shelfId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesShelfIdRoute = ShelvesShelfIdRouteImport.update({
  id: '/shelves/$shelfId',
  path: '/shelves/$shelfId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lending': typeof LendingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lending': typeof LendingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lending': typeof LendingRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lending'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/books/$bookId'
    | '/libraries/$libraryId'
    | '/shelves/$shelfId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lending'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/books/$bookId'
    | '/libraries/$libraryId'
    | '/shelves/$shelfId'
  id:
    | '__root__'
    | '/'
    | '/lending'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/books/$bookId'
    | '/libraries/$libraryId'
    | '/shelves/$shelfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LendingRoute: typeof LendingRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  ShelvesShelfIdRoute: typeof ShelvesShelfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/$shelfId': {
      id: '/shelves/$shelfId'
      path: '/shelves/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof ShelvesShelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LendingRoute: LendingRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  ShelvesShelfIdRoute: ShelvesShelfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
